name: dkg_player
description: Deterministic Kinetic Golem (DKG) Flutter player.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.10
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
